# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
                ('token', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('extra_charge', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('device_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialitySignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SsidSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=50)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.SignUp')),
            ],
        ),
    ]
