# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitysignup',
            name='signup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Minimum 8 character required!!!', regex='^.{8}$')]),
        ),
        migrations.AlterField(
            model_name='ssidsignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
    ]
