# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20171127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitysignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
        migrations.AlterField(
            model_name='ssidsignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
    ]
