# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_auto_20171127_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='hotel_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='specialitysignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
        migrations.AlterField(
            model_name='ssidsignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
    ]
