# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_auto_20171129_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='closing_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='device_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='hotel_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='signup',
            name='opening_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='token',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='specialitysignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
        migrations.AlterField(
            model_name='ssidsignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
    ]
