# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0018_auto_20171215_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialitysignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
        migrations.AlterField(
            model_name='ssidsignup',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Signup'),
        ),
    ]
