# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitysignup',
            name='signup',
        ),
        migrations.RemoveField(
            model_name='ssidsignup',
            name='signup',
        ),
        migrations.DeleteModel(
            name='Specialitysignup',
        ),
        migrations.DeleteModel(
            name='Ssidsignup',
        ),
    ]
