# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('signup', '0002_auto_20171217_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(default='', max_length=250)),
                ('extra_charge', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(auto_now=True)),
                ('closing_time', models.TimeField(auto_now=True)),
                ('device_id', models.CharField(default='', max_length=20)),
                ('hotel_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
