# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=250)),
                ('extra_charge', models.BooleanField(default=False)),
                ('vat', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(auto_now=True)),
                ('closing_time', models.TimeField(auto_now=True)),
                ('device_id', models.CharField(default='', max_length=20)),
                ('hotel_name', models.CharField(default='', max_length=150)),
                ('is_verify', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
