# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
