# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountowner', '0002_auto_20171221_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='device_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='extra_charge',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='hotel_name',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='vat',
            field=models.NullBooleanField(default=None),
        ),
    ]
