# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountowner', '0006_auto_20171221_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
    ]
