# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(default='local', max_length=30)),
                ('drink_type', models.CharField(choices=[('soft drink', 'soft drink'), ('hard drink', 'hard drink')], default='soft drink', max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/drink/')),
                ('descriptionm', models.TextField(blank=True, help_text='Enter a short description of this drink', max_length=400, null=True)),
            ],
            options={
                'ordering': ['drink_type'],
            },
        ),
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Drink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('food_type', models.CharField(blank=True, help_text='Eg: Italian, Continental, Asian', max_length=30, null=True)),
                ('course', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('snacks', 'snacks'), ('dinner', 'dinner')], default='snacks', max_length=30)),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/food/')),
                ('descriptionm', models.TextField(blank=True, help_text='Enter a short description of this food', max_length=400, null=True)),
            ],
            options={
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time', '-date'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-time', '-date'],
            },
        ),
        migrations.CreateModel(
            name='TodaySpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(default=0)),
                ('course', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('snacks', 'snacks'), ('dinner', 'dinner')], default='snacks', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='specialorder',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.TodaySpecial'),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
