# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20171126_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/drink/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/food/'),
        ),
    ]
