# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20171127_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='order',
        ),
        migrations.RemoveField(
            model_name='food',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Food'),
        ),
    ]
