# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20171127_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='drink_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='food_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
