# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20171127_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinkorder',
            options={'ordering': ['-time', '-date']},
        ),
        migrations.AlterModelOptions(
            name='foodorder',
            options={'ordering': ['-time', '-date']},
        ),
        migrations.AlterModelOptions(
            name='specialorder',
            options={'ordering': ['-time', '-date']},
        ),
        migrations.AddField(
            model_name='drinkorder',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specialorder',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
